### PR TITLE
Talk proposal for the meeting on 10-22-2024

### PR DESCRIPTION
**Pull request by ismailkuru**

### CODE REVIEW

**Comment by csgordon** [comment]
@ismailkuru so is this a proposal for you to give a talk about some thoughts?

**Comment by ismailkuru** [comment]
@csgordon yes.

**Comment by csgordon** [comment]
Okay, can you clarify that it's a talk, rather than a paper discussion
without a paper link?

**Comment by ismailkuru** [comment]
@csgordon I tried to clarify

**Pull request merged**
